version: '3.8'

services:
  web:
    container_name: DevBlog
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    volumes:
      - media:/app/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --noinput || true &&
             gunicorn --bind 0.0.0.0:8000 AyBlog.wsgi:application"
    restart: always

  db:
    container_name: postgresDb
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DbNAME}
      POSTGRES_USER: ${DbUSER}
      POSTGRES_PASSWORD: ${DbPASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  pgdata:
  media:
