version: '3.8'

services:
  db:
    container_name: postgresDb
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DbNAME}
      POSTGRES_USER: ${DbUSER}
      POSTGRES_PASSWORD: ${DbPASSWORD}
    networks:
      - webnet
    restart: always

  web:
    container_name: DevBlog
    build: 
      context: .
      args:
        - SECRET_KEY=${SECRET_KEY}
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DbNAME=${DbNAME}
      - DbUSER=${DbUSER}
      - DbPASSWORD=${DbPASSWORD}
      - DbHOST=${DbHOST}
      - DbPORT=${DbPORT}
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - webnet
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  webnet: