version: '3.8'

services:
  db:
    container_name: postgresDb
    build:
      context: .
      dockerfile: Dockerfile.db
    image: postgresdb:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DbNAME}
      POSTGRES_USER: ${DbUSER}
      POSTGRES_PASSWORD: ${DbPASSWORD}
    networks:
      - webnet
    restart: always

  web:
    container_name: DevBlog
    build: .
    image: devblog:latest
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DbNAME=${DbNAME}
      - DbUSER=${DbUSER}
      - DbPASSWORD=${DbPASSWORD}
      - DbHOST=${DbHOST}
      - DbPORT=${DbPORT}
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=core.settings
    networks:
      - webnet
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  webnet: